version: "2"

networks:
  proxy-web-network:
    external: true
  internal:
    external: false

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: delphi
    stdin_open: true
    tty: true
    labels:
      - traefik.backend=django
      - traefik.frontend.rule=Host:delphi.foussa.io
      - traefik.docker.network=proxy-web-network
      - traefik.port=80
    networks:
      - proxy-web-network
    restart: always
    volumes:
      - .:/var/www/delphi
