version: "2"

networks:
  proxy-web-network:
    external: true

services:
  oracle:
    build:
      context: .
      dockerfile: Dockerfile
    image: delphi
    stdin_open: true
    ports:
      - "6969:6969"
    tty: true
    networks:
      - proxy-web-network
    restart: always
    volumes:
      - .:/var/www/delphi
