# Generated by Django 2.2 on 2019-04-28 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePointPriorScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField()),
                ('seasonality', models.BooleanField()),
                ('currentPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('predictedPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('previousActualPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('previousPredictedPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('previousActualDate', models.DateField()),
                ('previousPredictedDate', models.DateField()),
                ('change_point_prior_scale', models.ManyToManyField(to='delphi.ChangePointPriorScale')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(max_length=5)),
                ('exchange', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delphi.Prediction')),
            ],
        ),
        migrations.AddField(
            model_name='prediction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delphi.Stock'),
        ),
    ]
