# Generated by Django 2.2 on 2019-04-28 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('delphi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='currentPrice',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='predictedPrice',
            new_name='predicted_price',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='previousActualDate',
            new_name='previous_actual_date',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='previousActualPrice',
            new_name='previous_actual_price',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='previousPredictedDate',
            new_name='previous_predicted_date',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='previousPredictedPrice',
            new_name='previous_predicted_price',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
